apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  type: LoadBalancer  # Automatically creates NodePort & ClusterIP
  ports:
    - protocol: TCP
      port: 80           # LoadBalancer listens on port 80
      targetPort: 8080   # Forward traffic to pod on 8080
